### ISSUE TITLE
Make new projects using the simulator

### ISSUE THREAD

**Issue by alejo9719** [megakilo/FreeRTOS-Sim#3]
Hi, I want to use your simulator for making FreeRTOS project tests before implementing the project on a microcontroller. To do it, I have been trying to run the examples for the standard edition of FreeRTOS (the ones used in the practical guide) using the simulator. I haven't been able to do it. I don't have much experience using this type of ports, so I could use your help.

Thank you.

**Comment by megakilo** [comment]
The Demo directory contains the examples using FreeRTOS API. You can also study the main.c from Project directory on how to add your code into the simulator. Then compile everything into an executable.
